name: Robo Loteria

on:
  schedule:
    - cron: '30 23 * * *' # Roda todas as noites às 20:30 (Horário de Brasília)
  workflow_dispatch:     # Cria um botão para você rodar manualmente quando quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Usar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Rodar script de atualizacao
      run: node atualizar.js
    - name: Salvar modificacoes no dados.json
      run: |
        git config --global user.name "Robo Loteria"
        git config --global user.email "bot@github.com"
        git add dados.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Dados das loterias atualizados" && git push)
